import { NextResponse } from 'next/server'

export async function GET(request) {
  // const token = process.env.TOKEN || 'nothing'

  // const { searchParams } = new URL(request.url)

  // let page = Number(searchParams.get('page') ?? '1')
  // let page_size = Number(searchParams.get('page_size') ?? '50')

  // const resp = await fetch(
  //   `https://sandbox.belvo.com/api/institutions/?page=${page}&page_size=${page_size}`,
  //   {
  //     headers: {
  //       Authorization: `Basic ${token}`,
  //     },
  //   }
  // )
  // const data = await resp.json()
  // if (data?.results?.length >= 0) {
  //   return NextResponse.json(data, { status: 200 })
  // } else {
  //   return NextResponse.json({ message: 'Page not found' }, { status: 404 })
  // }
  const data = {
    count: 15,
    next: null,
    previous: null,
    results: [
      {
        id: 9322,
        name: 'belvo_mx_retail',
        type: 'bank',
        code: null,
        website: null,
        display_name: 'Belvo Mx Retail',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#0AB0D8',
        logo: null,
        icon_logo: null,
        text_logo: null,
        form_fields: [
          {
            name: 'username',
            type: 'number',
            label: 'NIT',
            validation: '^[0-9]{1,15}$',
            placeholder: '1018470893',
            validation_message: 'Credenciales incorrectas',
          },
          {
            name: 'username2',
            type: 'number',
            label: 'Delay seconds',
            validation: '^[0-9]{1,6}$',
            placeholder: '10147593028',
            validation_message: '8 a 11 dígitos',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Contraseña',
            validation: '^.{1,}$',
            placeholder: '**********',
            validation_message: 'Contraseña incorrecta',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: ['ACCOUNTS', 'OWNERS'],
        openbanking_information: null,
      },
      {
        id: 1006,
        name: 'erebor_br_retail',
        type: 'bank',
        code: '1006',
        website: null,
        display_name: 'Erebor Bank',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/erebor.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1005,
        name: 'erebor_co_retail',
        type: 'bank',
        code: '1005',
        website: null,
        display_name: 'Erebor Bank',
        country_code: 'CO',
        country_codes: ['CO'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/erebor.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'username',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'password',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1004,
        name: 'erebor_mx_retail',
        type: 'bank',
        code: '1004',
        website: null,
        display_name: 'Erebor Bank',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/erebor.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/erebor.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'usuário',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'BALANCES',
          'INCOMES',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
        ],
        openbanking_information: null,
      },
      {
        id: 1012,
        name: 'gotham_br_business',
        type: 'bank',
        code: '1012',
        website: null,
        display_name: 'Gotham Business Bank',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/gotham.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/gotham.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/gotham.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: ['ACCOUNTS', 'TRANSACTIONS', 'OWNERS', 'BALANCES'],
        openbanking_information: null,
      },
      {
        id: 1003,
        name: 'gringotts_br_retail',
        type: 'bank',
        code: '1003',
        website: null,
        display_name: 'Gringotts Bank',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/gringotts.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1002,
        name: 'gringotts_co_retail',
        type: 'bank',
        code: '1002',
        website: null,
        display_name: 'Gringotts Bank',
        country_code: 'CO',
        country_codes: ['CO'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/gringotts.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'usuário',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1001,
        name: 'gringotts_mx_retail',
        type: 'bank',
        code: '1001',
        website: null,
        display_name: 'Gringotts Bank',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/gringotts.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/gringotts.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'username',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'password',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'BALANCES',
          'INCOMES',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
        ],
        openbanking_information: null,
      },
      {
        id: 1020,
        name: 'heimdall_br_retail',
        type: 'bank',
        code: '1020',
        website: null,
        display_name: 'Heimdall Bank (teste de MFA)',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/heimdall.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requer entre 1 e 16 caracteres',
          },
          {
            name: 'token',
            type: 'number',
            label: 'Token',
            length: '6',
            optional: true,
            validation: '^\\d{6}$',
            validation_message: 'Requiere 6 dígitos',
          },
        ],
        features: [
          {
            name: 'token_required',
            description:
              'institution may need a token during link creation / login',
          },
        ],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1021,
        name: 'heimdall_co_retail',
        type: 'bank',
        code: '1021',
        website: null,
        display_name: 'Heimdall Bank (Pruebas MFA)',
        country_code: 'CO',
        country_codes: ['CO'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/heimdall.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'username',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'password',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'token',
            type: 'number',
            label: 'Token',
            length: '6',
            optional: true,
            validation: '^\\d{6}$',
            validation_message: 'Requiere 6 dígitos',
          },
        ],
        features: [
          {
            name: 'token_required',
            description:
              'institution may need a token during link creation / login',
          },
        ],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 1014,
        name: 'heimdall_mx_retail',
        type: 'bank',
        code: '1014',
        website: null,
        display_name: 'Heimdall Bank (Pruebas MFA)',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/heimdall.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/heimdall.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'username',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'password',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'token',
            type: 'number',
            label: 'Token',
            length: '6',
            optional: true,
            validation: '^\\d{6}$',
            validation_message: 'Requiere 6 dígitos',
          },
        ],
        features: [
          {
            name: 'token_required',
            description:
              'institution may need a token during link creation / login',
          },
        ],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'BALANCES',
          'INCOMES',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
        ],
        openbanking_information: null,
      },
      {
        id: 1015,
        name: 'ironbank_br_business',
        type: 'bank',
        code: '1015',
        website: null,
        display_name: 'Iron Bank (Advanced login)',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/ironbank.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/ironbank.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/ironbank.svg',
        form_fields: [
          {
            name: 'username_type',
            type: 'select',
            values: [
              {
                code: '999',
                label: 'Identification (invalid)',
                validation: '^.{1,}$',
                validation_message: 'Credenciales incorrectas.',
                placeholder: 'Número de identificación.',
              },
              {
                code: '003',
                label: 'Passport (valid)',
                validation: '^.{1,}$',
                validation_message: 'Credenciales incorrectas.',
                placeholder: 'Número de identificación.',
              },
            ],
            placeholder: 'Opções de acesso',
            pre_selected: 0,
          },
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'username2',
            type: 'text',
            label: 'Conta 2',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password2',
            type: 'password',
            label: 'Senha 2',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: ['ACCOUNTS', 'TRANSACTIONS', 'OWNERS', 'BALANCES'],
        openbanking_information: null,
      },
      {
        id: 1016,
        name: 'ironbank_br_retail',
        type: 'bank',
        code: '1016',
        website: null,
        display_name: 'Iron Bank (Advanced login)',
        country_code: 'BR',
        country_codes: ['BR'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/ironbank.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/ironbank.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/ironbank.svg',
        form_fields: [
          {
            name: 'username_type',
            type: 'select',
            values: [
              {
                code: '999',
                label: 'Identification (invalid)',
                validation: '^.{1,}$',
                validation_message: 'Credenciales incorrectas.',
                placeholder: 'Número de identificación.',
              },
              {
                code: '003',
                label: 'Passport (valid)',
                validation: '^.{1,}$',
                validation_message: 'Credenciales incorrectas.',
                placeholder: 'Número de identificación.',
              },
            ],
            placeholder: 'Opções de acesso',
            pre_selected: 0,
          },
          {
            name: 'username',
            type: 'text',
            label: 'Conta',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'username2',
            type: 'text',
            label: 'Conta 2',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'Senha',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password2',
            type: 'password',
            label: 'Senha 2',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'ACCOUNTS',
          'TRANSACTIONS',
          'OWNERS',
          'RECURRING_EXPENSES',
          'RISK_INSIGHTS',
          'BALANCES',
          'INCOMES',
        ],
        openbanking_information: null,
      },
      {
        id: 9454,
        name: 'planet_mx_employment',
        type: 'employment',
        code: '9454',
        website: null,
        display_name: 'Planet Express Employment',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/planet_express_logo.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/planet_express_icon.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/planet_express_logo.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'CURP',
            validation: '^([A-Z]{4})([0-9]{6})([A-Z]{6})([A-Z0-9]{2})$',
            placeholder: 'Ej: LOLJ970312MBSPPN08',
            validation_message:
              'La CURP tiene que ser de 18 caracteres y mayúsculas',
          },
          {
            name: 'password',
            type: 'hidden',
            value: 'fake-password',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: ['EMPLOYMENT_RECORDS', 'OWNERS'],
        openbanking_information: null,
      },
      {
        id: 1013,
        name: 'tatooine_mx_fiscal',
        type: 'fiscal',
        code: '1013',
        website: null,
        display_name: 'Tatooine Fiscal',
        country_code: 'MX',
        country_codes: ['MX'],
        primary_color: '#056dae',
        logo: 'https://statics.sandbox.belvo.io/institutions/text_logos/tatooine.svg',
        icon_logo:
          'https://statics.sandbox.belvo.io/institutions/icon_logos/tatooine.svg',
        text_logo:
          'https://statics.sandbox.belvo.io/institutions/text_logos/tatooine.svg',
        form_fields: [
          {
            name: 'username',
            type: 'text',
            label: 'username',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            placeholder: '12345678901',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
          {
            name: 'password',
            type: 'password',
            label: 'password',
            validation: '^[a-zA-Z0-9_]{1,16}$',
            validation_message: 'Requiere 1 y 16 caracteres',
          },
        ],
        features: [],
        integration_type: 'credentials',
        status: 'healthy',
        resources: [
          'TAX_COMPLIANCE_STATUS',
          'TAX_RETURNS',
          'TAX_STATUS',
          'INVOICES',
        ],
        openbanking_information: null,
      },
    ],
  }
  setTimeout(() => {
    console.log('pasaron dos segundos')
  }, 2000)
  return NextResponse.json(data, { status: 200 })
}
